#!/usr/bin/env bash
# Regenerate the Orbits Windows app icon (windows/runner/resources/app_icon.ico)
# from the single source of truth, tool/branding/orbits_icon_source.png.
#
# You normally DON'T need this: windows/ is generated by `flutter create`, but the
# app_icon.ico is force-tracked (see .gitignore), and `flutter create` keeps an
# existing app_icon.ico — so a fresh checkout already builds with the Orbits icon
# and the taskbar/EXE show it. Run this only if you deleted windows/ or want to
# regenerate the icon (e.g. after changing the source PNG).
#
# Works anywhere bash runs, including Git Bash on Windows. Requires the Flutter
# SDK on PATH.
set -euo pipefail

# Repo root (this script lives in tool/windows/).
cd "$(dirname "$0")/../.."

if [ ! -d windows ]; then
  echo "windows/ missing — scaffolding it with flutter create…"
  flutter create --platforms=windows --org com.orbits --project-name orbits_flutter .
fi

echo "Generating native launcher icons (Android + Windows)…"
dart run flutter_launcher_icons -f flutter_launcher_icons.yaml

ico="windows/runner/resources/app_icon.ico"
test -s "$ico"
hash="$(sha256sum "$ico" | awk '{print $1}')"

# Fail loudly if generation left the default Flutter icon in place.
while IFS= read -r d; do
  case "$d" in ''|\#*) continue ;; esac
  if [ "$hash" = "$d" ]; then
    echo "ERROR: $ico is still the default Flutter icon ($hash)." >&2
    echo "       flutter_launcher_icons did not produce the Orbits icon." >&2
    exit 1
  fi
done < tool/windows/flutter_default_app_icon.sha256

echo "OK: $ico is the Orbits icon ($hash)."
echo "Tip: commit it with 'git add windows/runner/resources/app_icon.ico' if it changed."
