// Port of src/peer/helpers.js — peer id normalization + PeerJS error mapping.
//
// Keep behavior identical to the JS module; the UI relies on these exact
// strings and on the set of accepted id shapes.

import 'dart:convert' show jsonDecode, base64Url;

import 'package:shared_preferences/shared_preferences.dart';

import '../core/identity.dart' as identity;

/// Mirror of the `STORAGE` object literal in `src/peer/helpers.js`. Keys used
/// by the React build against `localStorage`; on Flutter they map to
/// `SharedPreferences` entries. Keep these byte-identical with the JS source
/// so a web/native dual-deploy can share the same keyspace without surprise
/// namespace drift.
abstract class StorageKeys {
  static const String peerId = 'orbits_peer_id';
  static const String knownPeers = 'orbits_known_peers';
  static const String messages = 'orbits_messages_v1';
  static const String blockedPeers = 'orbits_blocked_peers';
  static const String profiles = 'orbits_profiles_v1';
  static const String micSettings = 'orbits_mic_settings_v1';
  static const String powerSaver = 'orbits_power_saver';
  static const String peerLockPrefix = 'orbits_peer_lock:';
  static const String relayOnly = 'orbits_relay_only';
}

/// Normalize a raw peer id to the canonical form used everywhere in the
/// codebase — trimmed + **upper-case**. JS uses `toUpperCase()`; using
/// `toLowerCase()` here would quietly break peer discovery because the same
/// peerId would hash to a different string on the wire than in storage.
String normalizePeerId(String? raw) {
  if (raw == null) return '';
  return raw.trim().toUpperCase();
}

/// Accept legacy `ORBIT-` + 6 hex (24-bit) and new `ORBIT-` + 16 hex (64-bit).
/// New ids are generated by [identity.generatePeerId].
bool isValidPeerId(String? raw) {
  if (raw == null) return false;
  return identity.isValidPeerId(normalizePeerId(raw));
}

/// The stable QR/deep-link payload for sharing a contact. The reader
/// ([parseContactQrPayload]) also accepts a bare peerId and the legacy
/// shapes, so changing the *writer* to this form is backward-compatible.
String contactQrPayload(
  String peerId, {
  List<int>? discoverySecret,
  List<int>? identityPublicKey,
  String? deviceId,
  List<int>? transportPublicKey,
}) {
  final base = 'orbits://contact/${normalizePeerId(peerId)}';
  final q = <String>[];
  if (discoverySecret != null && discoverySecret.isNotEmpty) {
    q.add('d=${base64Url.encode(discoverySecret).replaceAll('=', '')}');
  }
  if (identityPublicKey != null && identityPublicKey.isNotEmpty) {
    q.add('i=${base64Url.encode(identityPublicKey).replaceAll('=', '')}');
  }
  if (deviceId != null && deviceId.isNotEmpty) {
    q.add('did=${Uri.encodeQueryComponent(deviceId)}');
  }
  if (transportPublicKey != null && transportPublicKey.isNotEmpty) {
    q.add('t=${base64Url.encode(transportPublicKey).replaceAll('=', '')}');
  }
  return q.isEmpty ? base : '$base?${q.join('&')}';
}

/// Shared contact-discovery secret from a QR query `d=`. Never the Peer ID.
List<int>? parseContactDiscoverySecret(String? raw) =>
    _parseQrBytesQuery(raw, 'd');

/// Identity SPKI from a QR query `i=`. Used to pin a contact before connect.
List<int>? parseContactIdentityPublicKey(String? raw) =>
    _parseQrBytesQuery(raw, 'i');

String? parseContactDeviceId(String? raw) => _parseQrStringQuery(raw, 'did');

List<int>? parseContactTransportPublicKey(String? raw) =>
    _parseQrBytesQuery(raw, 't');

List<int>? _parseQrBytesQuery(String? raw, String key) {
  final v = _parseQrStringQuery(raw, key);
  if (v == null || v.isEmpty) return null;
  var padded = v;
  final pad = (4 - padded.length % 4) % 4;
  padded = padded + ('=' * pad);
  try {
    final bytes = base64Url.decode(padded);
    return bytes.isEmpty ? null : bytes;
  } catch (_) {
    return null;
  }
}

String? _parseQrStringQuery(String? raw, String key) {
  if (raw == null) return null;
  final q = raw.trim().indexOf('?');
  if (q < 0) return null;
  final query = raw.trim().substring(q + 1);
  for (final part in query.split('&')) {
    final eq = part.indexOf('=');
    if (eq <= 0) continue;
    if (part.substring(0, eq) != key) continue;
    final value = part.substring(eq + 1);
    return value.isEmpty ? null : Uri.decodeQueryComponent(value);
  }
  return null;
}

/// Extract a canonical peerId from whatever a contact QR / pasted code holds,
/// or null if it doesn't look like an Orbits contact. Tolerant of:
///   • bare `ORBIT-ABC123` (any case, surrounding whitespace)
///   • `orbits://contact/ORBIT-ABC123`
///   • `orbits:contact:ORBIT-ABC123`
///   • JSON `{"type":"contact","peerId":"ORBIT-ABC123"}` (`id` accepted too)
/// Returns the normalized (trimmed, upper-cased) peerId, validated against
/// [isValidPeerId]. Shared by BOTH the scanner and the manual-entry field so
/// the two paths can never disagree about what's acceptable.
String? parseContactQrPayload(String? raw) {
  if (raw == null) return null;
  final s = raw.trim();
  if (s.isEmpty) return null;

  // JSON contact payload.
  if (s.startsWith('{')) {
    try {
      final obj = jsonDecode(s);
      if (obj is Map) {
        final type = obj['type'];
        if (type == null || type == 'contact') {
          final pid = obj['peerId'] ?? obj['id'];
          if (pid is String) {
            final n = normalizePeerId(pid);
            if (isValidPeerId(n)) return n;
          }
        }
      }
    } catch (_) {
      // Not valid JSON — fall through (it won't match anything else either).
    }
    return null;
  }

  // `orbits:` deep link. Accept ONLY an explicit CONTACT link
  // (`orbits://contact/<id>` or `orbits:contact:<id>`) — never a room/server
  // invite such as `orbits://room/<id>`. Drop any trailing query/fragment,
  // split on the separators, and require the `contact` marker before the id.
  // A trailing slash is tolerated.
  if (s.toLowerCase().startsWith('orbits:')) {
    var body = s;
    final cut = body.indexOf(RegExp(r'[?#]'));
    if (cut >= 0) body = body.substring(0, cut);
    final tokens =
        body.split(RegExp(r'[:/]')).where((p) => p.isNotEmpty).toList();
    // tokens[0] == 'orbits'; tokens[1] must be the explicit 'contact' segment.
    final isContactLink = tokens.length >= 3 &&
        tokens[0].toLowerCase() == 'orbits' &&
        tokens[1].toLowerCase() == 'contact';
    if (isContactLink) {
      final n = normalizePeerId(tokens.last);
      if (isValidPeerId(n)) return n;
    }
    return null;
  }

  // Bare peerId.
  final n = normalizePeerId(s);
  return isValidPeerId(n) ? n : null;
}

/// Canonical connection-map key. The JS source uses the same shape so a
/// cross-build shared storage layer (SharedPreferences / IndexedDB) hashes
/// to the same bucket.
String connKey(String remoteId, String channel) {
  final ch = channel == 'ephemeral' ? 'ephemeral' : 'reliable';
  return '${normalizePeerId(remoteId)}|$ch';
}

/// Millisecond epoch. Port of `src/peer/helpers.js::now()` — purely for
/// call-site parity; anyone new should just call `DateTime.now()`.
int now() => DateTime.now().millisecondsSinceEpoch;

/// Map a PeerJS error type into a user-facing Russian string. Mirrors
/// mapPeerError in helpers.js.
String mapPeerError(Object err) {
  final type = err is Map ? err['type'] : null;
  switch (type) {
    case 'unavailable-id':
      return 'Этот ID уже занят';
    case 'peer-unavailable':
      // The contact is saved locally regardless — this only means they aren't
      // reachable right now, NOT that the contact is missing/invalid.
      return 'Контакт сейчас не в сети';
    case 'invalid-id':
      return 'Недопустимый ID';
    case 'network':
      return 'Проблема с сетью';
    case 'server-error':
    case 'socket-error':
      return 'Ошибка сервера — переподключаемся…';
    case 'ssl-unavailable':
      return 'SSL недоступен';
    case 'browser-incompatible':
      return 'Ваш браузер не поддерживается';
    default:
      return 'Ошибка подключения';
  }
}

/// Paranoid mode setting — when true, WebRTC only accepts TURN-relay
/// candidates so the remote never sees our IP. Stored as `'1'`/`'0'` under
/// [StorageKeys.relayOnly] to stay byte-compatible with the React build's
/// localStorage entries.
Future<bool> isRelayOnlyEnabled() async {
  final prefs = await SharedPreferences.getInstance();
  return prefs.getString(StorageKeys.relayOnly) == '1';
}

Future<void> setRelayOnlyEnabled(bool value) async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setString(StorageKeys.relayOnly, value ? '1' : '0');
}
