name: orbits_transport_platform_interface
description: Platform interface for the Orbits Bare/Hyperswarm transport plugin.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.12.0 <3.13.0"

dependencies:
  plugin_platform_interface: ^2.1.8
