// Guards the force-tracked Windows app icon. The Windows EXE / window / taskbar
// / installer all draw from windows/runner/resources/app_icon.ico (compiled in
// via Runner.rc). That folder is generated by `flutter create` and mostly
// gitignored, so the icon is force-tracked — and this test fails loudly if it's
// missing, empty, or the DEFAULT Flutter logo, instead of letting a build ship
// the stock icon. Known-default hashes live in tool/windows/.
//
// Runs in plain `flutter test` (cwd = package root) on any host, because the
// .ico is committed.

import 'dart:io';

import 'package:crypto/crypto.dart' show sha256;
import 'package:flutter_test/flutter_test.dart';

void main() {
  const iconPath = 'windows/runner/resources/app_icon.ico';
  const defaultsPath = 'tool/windows/flutter_default_app_icon.sha256';

  test('Windows app_icon.ico is committed, valid, and not the default Flutter icon',
      () {
    final f = File(iconPath);
    expect(f.existsSync(), isTrue,
        reason: '$iconPath is missing. It is force-tracked (see .gitignore); '
            'regenerate with tool/windows/restore_app_icon.sh');

    final bytes = f.readAsBytesSync();
    expect(bytes.length, greaterThan(1000),
        reason: '$iconPath is empty/truncated');
    // .ico magic number: reserved(0,0) + type 1 (icon).
    expect(bytes.sublist(0, 4), const [0x00, 0x00, 0x01, 0x00],
        reason: '$iconPath is not a valid .ico file');

    final hash = sha256.convert(bytes).toString();
    final defaults = _knownDefaultHashes(defaultsPath);
    expect(defaults, isNotEmpty,
        reason: '$defaultsPath has no known-default hashes to compare against');
    expect(
      defaults.contains(hash),
      isFalse,
      reason: '$iconPath is the DEFAULT Flutter icon (the blue logo) — the '
          'Windows taskbar/EXE/installer would show it instead of Orbits. '
          'Regenerate it: run tool/windows/restore_app_icon.sh (or '
          '`dart run flutter_launcher_icons -f flutter_launcher_icons.yaml` '
          'after `flutter create`), then commit the .ico.',
    );
  });
}

Set<String> _knownDefaultHashes(String path) {
  final f = File(path);
  if (!f.existsSync()) return <String>{};
  return f
      .readAsLinesSync()
      .map((l) => l.trim())
      .where((l) => l.isNotEmpty && !l.startsWith('#'))
      .toSet();
}
